version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    image: python-celery:240630
    container_name: celery
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    env_file:
      - .env
    command: sh -c "celery -A crm worker -l info"