# Generated by Django 4.2.11 on 2024-05-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModelTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('basicmodeltemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.basicmodeltemplate')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('category', models.CharField(choices=[('Блок', 'Thema'), ('Коментарий', 'Comment'), ('К выполнению', 'Task')], max_length=16)),
                ('notes_relations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_parent', to='notes.notes')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
            bases=('notes.basicmodeltemplate',),
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('basicmodeltemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.basicmodeltemplate')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('Администратор', 'Admin'), ('Руководитель', 'Manager'), ('Работник', 'Employee'), ('Килент', 'Client'), ('Оператор', 'Operaton')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
            bases=('notes.basicmodeltemplate',),
        ),
        migrations.CreateModel(
            name='NotesReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.IntegerField()),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notereactions_to_note', to='notes.notes')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notereactions_to_profile', to='notes.profiles')),
            ],
            options={
                'verbose_name': 'note reaction',
                'verbose_name_plural': 'note reactions',
            },
        ),
        migrations.CreateModel(
            name='NotesToProfiles',
            fields=[
                ('basicmodeltemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.basicmodeltemplate')),
                ('role', models.CharField(choices=[('Отвественный', 'Owner'), ('Исполнитель', 'Executor'), ('Наблюдаель', 'Spectator'), ('Постановщик', 'Assignor')], max_length=20)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_profiles', to='notes.notes')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_notes', to='notes.profiles')),
            ],
            options={
                'verbose_name': 'Notes Profile Relation',
                'verbose_name_plural': 'Notes Profile Relations',
                'unique_together': {('note_id', 'profile_id')},
            },
            bases=('notes.basicmodeltemplate',),
        ),
        migrations.AddConstraint(
            model_name='notesreaction',
            constraint=models.UniqueConstraint(fields=('note_id', 'profile_id'), name='unique_note_profile'),
        ),
    ]
