# Generated by Django 4.2.11 on 2024-05-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('Блок', 'Topic'), ('К выполнению', 'Task'), ('Коментарий', 'Comment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes_relations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_parent', to='notes.notes'),
        ),
    ]
