# Generated by Django 4.2.11 on 2024-05-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='notes_relations',
        ),
        migrations.CreateModel(
            name='NoteStructureModel',
            fields=[
                ('basicmodeltemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.basicmodeltemplate')),
                ('category', models.CharField(choices=[('Проект', 'Topic'), ('Задача', 'Task'), ('Руководство', 'Instruction'), ('Коментарий', 'Comment'), ('Фокус', 'Key Comment')], max_length=16)),
                ('current_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_structure_current', to='notes.notes')),
                ('parent_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_structure_parent', to='notes.notes')),
                ('root_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_structure_root', to='notes.notes')),
            ],
            bases=('notes.basicmodeltemplate',),
        ),
    ]
