# Generated by Django 4.2.11 on 2024-05-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_category_remove_notes_notes_relations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notestructuremodel',
            name='category',
            field=models.CharField(choices=[('topic', 'Проект'), ('task', 'Задача'), ('instruction', 'Руководство'), ('comment', 'Коментарий'), ('key_comment', 'Фокус')], max_length=16),
        ),
    ]
