# Generated by Django 4.2.11 on 2024-05-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notestructuremodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notestructuremodel',
            name='current_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_structure_current', to='notes.notes'),
        ),
    ]
