# Generated by Django 4.2.11 on 2024-05-02 06:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='notes',
            constraint=models.UniqueConstraint(fields=('note', 'profile_id'), name='unique_note_profile'),
        ),
        migrations.AddField(
            model_name='notesreaction',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_reacts_note', to='notes.profiles'),
        ),
    ]
