# Generated by Django 4.2.11 on 2024-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notesreaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notesreaction',
            name='unique_note_profile',
        ),
        migrations.AddConstraint(
            model_name='notesreaction',
            constraint=models.UniqueConstraint(fields=('note_id', 'profile_id'), name='unique_note_profile'),
        ),
    ]
